version: "2"
services:
  jupyter:
    build: .
    volumes:
      - $PWD/script:/tmp/working
    working_dir: /tmp/working
    ports:
      - 8888:8888
    restart:
      always
    command: jupyter notebook --ip=0.0.0.0 --allow-root --no-browser
