version: "2.3"
services:
  lab:
    build: .
    user: $(id -u $USER):$(id -g $USER)
    volumes:
      - $PWD/script:/tmp/working
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
    working_dir: /tmp/working
    runtime: nvidia
    ports:
      - 8888:8888
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.password='sha1:47db3a1f0f2f:3adbeea3c88bd6a5bab02d5bd6e97b6b891e6ed9'
    restart: always
